kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: unity-nas
  annotations:
    description: for eksa testing
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2022-03-10T06:48:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: csi-unity.dellemc.com
parameters:
  arrayId: VIRT2148DRW2V6
  isDataReductionEnabled: 'false'
  nasServer: 'nas_2'
  protocol: NFS
  storagePool: 'pool_1'
  thinProvisioned: 'true'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
