apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-powerstore-ext4
  labels:
    name: mysql-pv-claim-powerstore-ext4
    csi: powerstore-ext4
spec:
  storageClassName: powerstore-ext4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
