apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-unity-nas
spec:
  storageClassName: unity-nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
