kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: unity-nas
  annotations:
    description: unity storage class for eksa testing
provisioner: csi-unity.dellemc.com
parameters:
  arrayId: VIRT2148DRW2V6
  isDataReductionEnabled: 'false'
  nasServer: 'nas_2'
  protocol: NFS
  storagePool: 'pool_1'
  thinProvisioned: 'true'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
